# Generated by Django 4.0.6 on 2022-08-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshopapp', '0012_alter_profile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
