# Generated by Django 4.0.6 on 2022-08-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshopapp', '0013_remove_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
